### PR TITLE
Add timezone support

### PR DESCRIPTION
**Pull request by greenday2**
As requested in https://github.com/yourlabs/django-cities-light/pull/81

* Add `City.timezone` field and `City.get_timezone_info()` method
* New dependency on pytz

### CODE REVIEW

**Comment by max-arnold** [comment]
@st4lk It would be nice if you review this PR

**Comment by jpic** [comment]
Overall it looks very good, but I'm not sure about timezone being a non-indexed CharField.

How does this compare to two other options:

- generate a TIMEZONE_CHOICES based on pytz, and have an IntegerField instead of a CharField ?
- have a Timezone model.

**Comment by jpic** [comment]
In that case, do we want to add db_index=True at least ?

Is there any reason we shouldn't use django-timezone-field ?

**Comment by max-arnold** [comment]
I do not see any use-cases for lookups on City.timezone (select all cities in given timezone?) to add an index. But we can add it if you think it is necessary.

Will look if django-timezone-field offers something useful to use it and worth adding another dependency. I'm also considering making dependency on pytz optional.

-1 on denormalizing (another table to update, add abstract model, dump fixtures - lots of complexity)

**Comment by jpic** [comment]
It could be used for aggregation by the users for example, but it can be
done later so it looks like time to integrate this patch unless there's
still any objection ?

**Comment by max-arnold** [comment]
@greenday2 Could you please add timezone field to City admin (both to the list view and to search)? Also it would be nice to have pytz-based validator for the model field (useful for the admin) and additionally run it at import time before assigning timezone value to the field.

**Pull request merged**
