### PR TITLE
Fixed missing migration files, when creating a migration for your local ...

### PR DESCRIPTION
**Pull request by drivard**
...app including this package it forces the migration to be created in the virtualenv folder. Once you have created each member of the team must create this migration file. Forcing to create it at the application layer is better because it is share among all the users at the same time.

### CODE REVIEW

**Comment by jpic** [comment]
Are you still interrested in contributing this ?

**Comment by drivard** [comment]
Hi James,

We already did through this branch. You told me how to merged and repackage.
https://github.com/yourlabs/django-cities-light/commit/842c92c5048dfaab1670837b314d0ffc47b42c7b

Want me to close the branch?

Thanks
Dominick

On Mon, Jan 12, 2015 at 3:43 AM, James Pic <notifications@github.com> wrote:

> Are you still interrested in contributing this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yourlabs/django-cities-light/pull/68#issuecomment-69541065>
> .
>



-- 
Bonne journée!
Dominick

**Comment by jpic** [comment]
Absolutely, yes it should be closed then.

Thanks again B)

**Comment by drivard** [comment]
done and implemented in https://github.com/yourlabs/django-cities-light/tree/fix_68

**Pull request closed without merging**
