### PR TITLE
translation_items_pre_import signal

### PR DESCRIPTION
**Pull request by FaBay89**
The signal is useful to import translation data in my own model. So you can save translations with the language code.

Alternatively i could implement a translation model completely if you are interested in. Maybe with an option to generate this model.

### CODE REVIEW

**Comment by jpic** [comment]
Sounds ok, @max-arnold ?

**Comment by max-arnold** [comment]
I'm not yet familiar with translation parser, but here are my two cents:

* The docs should be updated too (https://github.com/yourlabs/django-cities-light/blob/stable/3.x.x/docs/source/index.rst)
* What about adding default signal handler? Maybe it is better to move some existing code which skips translations (like `if len(items) > 5`) to the handler?
* Is there any need for symmetrical `translation_items_post_import` signal handler?

**Comment by max-arnold** [comment]
@FaBay89 Could you please elaborate a bit more on use cases you want to solve with custom translation model? How do you want to use translated geonames data in your application?

Is it enough for you to have two translations for each geonames object - one in its native language and other in English or translit? Or you want each object to be translated to as many languages as possible?

**Comment by FaBay89** [comment]
- First, i dont see any need for `translation_items_post_import`, because they dont have their own instance you can edit.
- Default signal handler woud be ok, but then i would have to unregister it, because of how i use the signal...

Why i need the translated names: the city.name does not specify any language the name comes from. So many cities in germany got the german name, but some, like munich, got the english one. Furthermore i want to display the names in different (specified) languages.

How i use the signal: The handler skips all unnecessary entries. Then it generates the `translation_data` like `translation_parse` would do. At the end it will ALWAYS raise a `InvalidItem`, so `translation_parse` does nothing anymore. The `translation_import` work as expected with the data from the signal handler. The reason is that i want to specify on my own which entries are skipped (in especially `len(items) > 5` skip to much entries, some short entries are the preferred ones).

The alternate names of the cities (and regions/countries) are saved in their own model. The City model get a new function `get_name_for_lang(self, lang)` which search for the preferred name in the specified language. 
To avoid to many entries in `alternate_names`, i used a fallback to City.name if the translation is equal to City.name (and is not preferred, because otherwise it could return an unprefered name).

So this behaviour produce only 125 alternate names for the 400 biggest cities (+regions/country) in germany with language setting `['de', 'en', 'abbr']`. (This was for testing only, later i want to import some more languages)

I thought about to integrate the alternate names (one field for every language?) in the City Model, but i think this way is more flexible and easier to handle with.

**Comment by jpic** [comment]
If we really want to add languages support inside our models, we should perhaps use something like django-modeltranslation, that's able to add a column per field_lang ie. name_fr, name_de, name_en, and so on, and then pickup the best one for the request language on display.

Meanwhile, this signal works for me, if there's no use case to mirror it then maybe it's wise to wait until we have an actual use case before we add code.

**Pull request merged**
