### PR TITLE
Use geoname_id as the only lookup method to update records

### LINKED ISSUE #110: Not importing all cities
When I run the import script, it seems to skip ~6k cities.

I am using CITIES_LIGHT_CITY_SOURCES = ['http://download.geonames.org/export/dump/cities1000.zip']
Mac box:
Django 1.9.2
Cities_light 3.2.0
Python 2.7.9 
MYSQL 5.6.21

Linux box: Centos
Django 1.9.2
Cities_light 3.2.0
Python 2.7.11
MYSQL 5.5.48-cll

example of how it is skipping entries:
2992741 Monte-Carlo (NOT IMPORTING)
2993458 Monaco  (IMPORTING)
3009937 La Condamine    (NOT IMPORTING)

I end up with 139769 entries in my cities table, but the cities1000.txt file has 145741 lines. 
There are no error messages at all and when I look through the log the "2992741" or "Monte-Carlo" never shows up.

### PR DESCRIPTION
**Pull request by max-arnold**
This was suggested some time ago in the mailing list: https://groups.google.com/forum/#!topic/yourlabs/aYwK3UgbAd8

Changelog:

* Geoname_id is the only lookup method during row update procedure (complex lookup logic is gone)
* **All** fields are updated, including slugs (use --keep-slugs to prevent that). Previously, updates in geonames.org's source files weren't propagated to the database. Also fixed bizarre behaviour when alternate_names/search_names accumulated after each update
* Geoname_id field is visible/searchable in Django admin
* Several new tests for update procedure, to check that records are correctly updated or added, including --noinsert option. Import/update tests now inherit from the same base class.
* New (failing) test to check that records are removed. The test is disabled, because removal is not yet implemented
* Speed improvements

Unfortunately, this didn't fix #110 and the improvement in number of imported cities is very low. As is turned out, lots of cities are skipped due to database constraints `unique_together = (('region', 'name'), ('region', 'slug'))`. Removal of these constraints is out of scope of this branch.

### CODE REVIEW

**Comment by max-arnold** [comment]
@jpic Review/approval would be nice, if you have some time.

**Comment by jpic** [comment]
Well, I've read it and you know the story: give a developer 10 lines of code it'll find 10 problems, give him 1000 lines and it'll say "no problem !". But if we take time I'd be happy to talk about it ;)

I've seen some patching feature, is this enabling you to patch geonames data before import like we discussed at europycon ?

Perhaps a good improvement to this PR could be done in the docs/ directory ?

**Comment by max-arnold** [comment]
No, there is no patching yet. Just more robust update procedure to actually *update* the data. The only field which does not change during update is geoname_id. The main commit in this branch is https://github.com/yourlabs/django-cities-light/pull/144/commits/4448ee267a3bf5cafb8f683ccff416726428388d

**Comment by max-arnold** [comment]
Patcher will be developed in a separate branch, but there is a long way to go: https://github.com/max-arnold/django-cities-light/commits/rewrite

**Comment by jpic** [comment]
Awesome, you've proven your dedication by supporting our userbase, you've got my approval to deploy this and move on, if you want me to actually try the code and make a proper line by line review I can try this week end.

**Comment by max-arnold** [comment]
Ok, I'll merge it to the master tomorrow. Also I think it will be wise to wait some time before making a new release, giving people a chance to spot possible problems in the master branch.

**Pull request merged**
