### PR TITLE
add subregion (admin2Codes) clean PR

### PR DESCRIPTION
**Pull request by Guts**
Same player, try again: #159.
Replace #169.

### CODE REVIEW

**Comment by Guts** [comment]
@jpic your comments ar welcome 💬

**Comment by jpic** [comment]
Sounds like you made dcl 4.0 ;)
@max-arnold  ?

**Comment by max-arnold** [comment]
I'll try to review the PR this weekend.

**Comment by Guts** [comment]
ping @jpic @max-arnold

**Comment by max-arnold** [comment]
@Guts Do the tests pass on your machine?

**Comment by Guts** [comment]
@max-arnold I didn't test everything because tests are already failing on master branch (Travis and in local). Do you have some test guidelines that I can use?

**Comment by Guts** [comment]
Duplicate of #188 

Thanks to @adamb70 👍

**Comment by Guts** [comment]
Duplicate of #188 

Thanks to @adamb70 👍

**Comment by Guts** [comment]
Duplicate of #188 

Thanks to @adamb70 👍

**Comment by Guts** [comment]
Duplicate of #188 

Thanks to @adamb70 👍

**Comment by Guts** [comment]
Duplicate of #188 

Thanks to @adamb70 👍

**Comment by Guts** [comment]
Duplicate of #188 

Thanks to @adamb70 👍

**Pull request closed without merging**
