### PR TITLE
Adds the possibility to customize the alternate_names separator

### PR DESCRIPTION
**Pull request by magnunleno**
In some languages the comma (`,`) is commonly used to separate compound names (country, region or city), and the usage of the comma as a "alternate name" separator can lead to some issues.

Example:
```
# select name, alternate_names from core_country where id=121;
    name     |                    alternate_names                    
-------------+-------------------------------------------------------
 North Korea | Coreia, Norte,República Popular Democrática da Coreia
```

Actually, in this example, North Korea has 2 alternate names "Coreia, Norte" and "República Popular Democrática da Coreia". 

This PR proposes a new setting option called `CITIES_LIGHT_ALTERNATE_NAME_SEP`. When can be configured to any character. In this example I used `;`:

```
# select name, alternate_names from core_country where id=121;
    name     |                    alternate_names                    
-------------+-------------------------------------------------------
 North Korea | Coreia, Norte;República Popular Democrática da Coreia
```

Which can be parsed without any issue.

Thanks for this great app!

### CODE REVIEW

**Comment by max-arnold** [comment]
If comma is broken by default, maybe it is worth making ';' the default separator value without introducing new setting? As far I can see, it is already used in alternateNames.txt:

```
% grep ';' alternateNames.txt

4309191	4030930		McKean Atoll; McKean Island
4309222	4030953		Enderbury Atoll; Enderbury Island
4309227	4030964		Caroline Atoll ; Caroline Island
4309236	4030968		Birnie Atoll; Birnie Island
10147673	7922099	fr	mosquée de Melek el-Saleh, abou-Rezêk ;				1
7911650	8411068		48.3 Km to Piacenza; 7.9 km to Ferriere
8026953	8458800		P.C.E.A High School; Pre-School
8889316	8813563		Bon Accord; Bellerts; Tablelan
9318617	9139644	no	Kyrkjedørsnuten; søre
10929372	10400589		Panjang Jembatan = 5.438 m ; Lebar Jembatan = 30 m
```

@jpic ?

**Comment by jpic** [comment]
Makes sense !

**Comment by magnunleno** [comment]
It's a possibility. I suggested the config option just for backward compatibility.

**Comment by magnunleno** [comment]
Done. Also removed the tests,

**Comment by max-arnold** [comment]
@magnunleno You also need to change fixtures (see travis test failures)

**Comment by jpic** [comment]
Nice one !

Note that you could just remove the fixture file and re-run the test: it would have regenerated it (it's done with django-dbdiff).

Keep up the great work !

:guitar:

**Pull request merged**
