### PR TITLE
Force utf8 encoding on all operatingsystem when platform is Python 3

### PR DESCRIPTION
**Pull request by mikaelosterberg**
Fixes python 3 encoding problems on consoles that don't support uft-8 like Windows CMD.

### CODE REVIEW

**Comment by jpic** [comment]
You rock !

Are you interrested in merging and releasing tasks as described in docs.yourlabs.org ?

**Comment by jpic** [comment]
Released in 3.0.4.

Welcome to AUTHORS, you rock, keep up the great work B)

Since you're a Windows user who is actually able to code, I'm inviting you to join our core-dev team.

**Comment by suquant** [comment]
You forgot to create git branch in releases

**Comment by jpic** [comment]
What do you mean ?

**Comment by suquant** [comment]
https://github.com/yourlabs/django-cities-light/releases

**Comment by jpic** [comment]
Pushed 3.0.4 tag.

Thanks @suquant

**Comment by suquant** [comment]
When i update some packages in projects i also read change-log
And today when a saw update for django-cities-light i went to look this log and saw

```
...
Upgrade
See CHANGELOG.
...
``` 
It not good practice :)
If possible, please write detailed list of changes

Thank you, you are best!

**Comment by jpic** [comment]
On Fri, Jan 30, 2015 at 1:43 PM, Georgy Kutsurua <notifications@github.com>
wrote:

> It not good practice :)
> If possible, please write detailed list of changes
>
If there is any action to upgrade, it should be detailed in the CHANGELOG.

For this release, there is no action to take, just upgrade as usual with
pip install -U django-cities-light.

Pull requests are welcome.


-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Pull request merged**
