### PR TITLE
Fix region pre import signal connection

### PR DESCRIPTION
**Pull request by st4lk**

### CODE REVIEW

**Comment by st4lk** [comment]
Sorry, looks like duplicate of #79

**Comment by jpic** [comment]
It seems like it was already fixed by bc8702337 wasn't it ?

**Comment by st4lk** [comment]
Yes, commit bc8702337adc439969f722ee19b37c4d69fed7b1 includes the fix.

**Comment by jpic** [comment]
Nice, thanks Alexey !

**Pull request closed without merging**
